# Generated by Django 5.2.8 on 2025-11-28 16:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Kategori Adı")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ürün Adı")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="URL"),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "metal_type",
                    models.CharField(
                        choices=[
                            ("gold", "Altın"),
                            ("silver", "Gümüş"),
                            ("platinum", "Platin"),
                            ("rose_gold", "Rose Altın"),
                            ("white_gold", "Beyaz Altın"),
                        ],
                        max_length=20,
                        verbose_name="Metal Tipi",
                    ),
                ),
                (
                    "karat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("8", "8 Ayar"),
                            ("14", "14 Ayar"),
                            ("18", "18 Ayar"),
                            ("22", "22 Ayar"),
                            ("24", "24 Ayar"),
                        ],
                        max_length=2,
                        verbose_name="Ayar",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Ağırlık (gram)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Fiyat (TL)",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stok")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="products/%Y/%m/%d/",
                        verbose_name="Ürün Resmi",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Satışta"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Öne Çıkan"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün",
                "verbose_name_plural": "Ürünler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/%Y/%m/%d/", verbose_name="Resim"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alternatif Metin"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Resmi",
                "verbose_name_plural": "Ürün Resimleri",
                "ordering": ["created_at"],
            },
        ),
    ]
