# Generated by Django 5.2.8 on 2025-11-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_best_seller",
            field=models.BooleanField(default=False, verbose_name="Çok Satan"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_recommended",
            field=models.BooleanField(default=False, verbose_name="Önerilen"),
        ),
    ]
