# Generated by Django 5.2.8 on 2025-12-02 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_stock_product_stock_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["order", "created_at"],
                "verbose_name": "Ürün Resmi",
                "verbose_name_plural": "Ürün Resimleri",
            },
        ),
        migrations.AddField(
            model_name="productimage",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Sıra"),
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to="products/videos/%Y/%m/%d/", verbose_name="Video"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        upload_to="products/video_thumbnails/%Y/%m/%d/",
                        verbose_name="Video Önizleme",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Başlık"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="products.product",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Videosu",
                "verbose_name_plural": "Ürün Videoları",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
