# Generated by Django 5.2.8 on 2025-12-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_productimage_options_productimage_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="is_video",
            field=models.BooleanField(default=False, verbose_name="Video mu?"),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Kategori Resmi"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Ürün Resmi"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.URLField(max_length=500, verbose_name="Resim"),
        ),
        migrations.DeleteModel(
            name="ProductVideo",
        ),
    ]
