# Generated by Django 5.2.8 on 2025-12-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productimage_is_video_alter_category_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/",
                verbose_name="Kategori Resmi (Dosya)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="Ürün Resmi (Dosya)",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/gallery/",
                verbose_name="Resim (Dosya)",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Kategori Resmi (URL)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Ürün Resmi (URL)"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Resim (URL)"
            ),
        ),
    ]
